LABELS = {
    1: 'A-1:Niebezpieczny zakręt w prawo',
    2: 'A-11:Nierówna droga',
    3: 'A-11a:Próg zwalniający',
    4: 'A-12a:Zwężenie jezdni - dwustronne',
    5: 'A-14:Roboty drogowe',
    6: 'A-15:Śliska jezdnia',
    7: 'A-16:Przejście dla pieszych',
    8: 'A-17:Dzieci',
    9: 'A-18b:Zwierzęta dzikie',
    10: 'A-2:Niebezpieczny zakręt w lewo',
    11: 'A-20:Odcinek jezdni o ruchu dwukierunkowym',
    12: 'A-21:Tramwaj',
    13: 'A-24:Rowerzyści',
    14: 'A-29:Sygnały świetlne',
    15: 'A-3:Niebezpieczne zakręty: pierwszy w prawo',
    16: 'A-30:Inne niebezpieczeństwo',
    17: 'A-32:Oszronienie jezdni',
    18: 'A-4:Niebezpieczne zakręty: pierwszy w lewo',
    19: 'A-6a:Skrzyżowanie z drogą podporządkowaną występującą po obu stronach',
    20: 'A-6b:Skrzyżowanie z drogą podporządkowaną występującą po prawej stronie',
    21: 'A-6c:Skrzyżowanie z drogą podporządkowaną występującą po lewej stronie',
    22: 'A-6d:Wlot drogi jednokierunkowej z prawej strony',
    23: 'A-6e:Wlot drogi jednokierunkowej z lewej strony',
    24: 'A-7:Ustąp pierwszeństwa',
    25: 'A-8:Skrzyżowanie o ruchu okrężnym',
    26: 'B-1:Zakaz ruchu w obu kierunkach',
    27: 'B-18:Zakaz wjazdu pojazdów o rzeczywistej masie całkowitej ponad ... t.',
    28: 'B-2:Zakaz wjazdu',
    29: 'B-20:STOP',
    30: 'B-21:Zakaz skręcania w lewo',
    31: 'B-22:Zakaz skręcania w prawo',
    32: 'B-25:Zakaz wyprzedzania',
    33: 'B-26:Zakaz wyprzedzania przez samochody ciężarowe',
    34: 'B-27:Koniec zakazu wyprzedzania',
    35: 'B-33:Ograniczenie prędkości',
    36: 'B-34:Koniec ograniczenia prędkości',
    37: 'B-36:Zakaz zatrzymywania się',
    38: 'B-41:Zakaz ruchu pieszych',
    39: 'B-42:Koniec zakazów',
    40: 'B-43:Strefa ograniczonej prędkości',
    41: 'B-44:Koniec strefy ograniczonej prędkości',
    42: 'B-5:Zakaz wjazdu samochodów ciężarowych',
    43: 'B-6-B-8-B-9:Zakaz wjazdu pojazdów innych niż samochodowe',
    44: 'B-8:Zakaz wjazdu pojazdów zaprzęgowych',
    45: 'B-9:Zakaz wjazdu rowerów',
    46: 'C-10:Nakaz jazdy z lewej strony znaku',
    47: 'C-12:Ruch okrężny',
    48: 'C-13:Droga dla rowerów',
    49: 'C-13-C-16:Droga dla pieszych i rowerzystów',
    50: 'C-13a:Koniec drogi dla rowerów',
    51: 'C-13a-C-16a:Koniec drogi dla pieszych i rowerzystów',
    52: 'C-16:Droga dla pieszych',
    53: 'C-2:Nakaz jazdy w prawo za znakiem',
    54: 'C-4:Nakaz jazdy w lewo za znakiem',
    55: 'C-5:Nakaz jazdy prosto',
    56: 'C-6:Nakaz jazdy prosto lub w prawo',
    57: 'C-7:Nakaz jazdy prosto lub w lewo',
    58: 'C-9:Nakaz jazdy z prawej strony znaku',
    59: 'D-1:Droga z pierwszeństwem',
    60: 'D-14:Koniec pasa ruchu',
    61: 'D-15:Przystanek autobusowy',
    62: 'D-18:Parking',
    63: 'D-18b:Parking zadaszony',
    64: 'D-2:Koniec drogi z pierwszeństwem',
    65: 'D-21:Szpital',
    66: 'D-23:Stacja paliwowa',
    67: 'D-23a:Stacja paliwowa tylko z gazem do napędu pojazdów',
    68: 'D-24:Telefon',
    69: 'D-26:Stacja obsługi technicznej',
    70: 'D-26b:Myjnia',
    71: 'D-26c:Toaleta publiczna',
    72: 'D-27:Bufet lub kawiarnia',
    73: 'D-28:Restauracja',
    74: 'D-29:Hotel (motel)',
    75: 'D-3:Droga jednokierunkowa',
    76: 'D-40:Strefa zamieszkania',
    77: 'D-41:Koniec strefy zamieszkania',
    78: 'D-42:Obszar zabudowany',
    79: 'D-43:Koniec obszaru zabudowanego',
    80: 'D-4a:Droga bez przejazdu',
    81: 'D-4b:Wjazd na drogę bez przejazdu',
    82: 'D-51:Automatyczna kontrola prędkości',
    83: 'D-52:Strefa ruchu',
    84: 'D-53:Koniec strefy ruchu',
    85: 'D-6:Przejście dla pieszych',
    86: 'D-6b:Przejście dla pieszych i przejazd dla rowerzystów',
    87: 'D-7:Droga ekspresowa',
    88: 'D-8:Koniec drogi ekspresowej',
    89: 'D-9:Autostrada',
    90: 'D-tablica:Zbiorcza tablica informacyjna',
    91: 'G-1a:Słupek wskaźnikowy z trzema kreskami umieszczany po prawej stronie jezdni',
    92: 'G-3:Krzyż św. Andrzeja przed przejazdem kolejowym jednotorowym'
}
